n = input ('Digite seu nome: ')
print (n.isspace())
print (n.isalnum())
print (n.isalpha())
print (n.isnumeric())
print (n.isascii())
print (n.isdecimal())
print (n.isdigit())
print (n.isidentifier())
print (n.isupper())
print (n.islower())
print (n.istitle())
print (n.isprintable())